# src/strataframe/contracts/step2_outputs.py
from __future__ import annotations

REP_CSV_HEADER = [
    "rep_id",
    "cell_id",
    "cell_tag",
    "score",
    "url",
    "kgs_id",
    "api",
    "api_num_nodash",
    "operator",
    "lease",
    "lat",
    "lon",
    "las_path",
    "picked_gr",
    "picked_por",
    "picked_den",
    "picked_neu",
    "picked_pe",
    "picked_dt",
]

CELL_TYPEWELL_HEADER = [
    "cell_id",
    "grid_ix",
    "grid_iy",
    "n_kernel",
    "n_read",
    "n_used",
    "template_path",
    "type_url",
    "type_las_path",
    "thickness_median",
    "ntg_median",
    "iqr_median",
    "error",
]

REP_PLACEMENT_HEADER = [
    "rep_id",
    "cell_id",
    "url",
    "las_path",
    "status",
    "thickness",
    "expected_thickness",
    "z_top",
    "z_base",
    "placed_z_top",
    "placed_z_base",
    "short_flag",
    "missing_top_flag",
    "missing_base_flag",
    "condensed_flag",
    "match_j_start",
    "match_j_end",
    "match_s_start",
    "match_s_end",
    "match_span",
    "warp_ratio",
    "dtw_cost_per_step",
    "error",
]
